# Generated by Django 2.0.4 on 2018-04-30 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0002_remove_myuser_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filetype',
            options={'permissions': (('view_filetype', 'Can see available tasks'), ('change_filetype_status', 'Can change the status of tasks'), ('close_filetype', 'Can remove a task by setting its status as closed')), 'verbose_name': '文档目录', 'verbose_name_plural': '文档目录'},
        ),
    ]
