# Generated by Django 2.0.4 on 2018-04-30 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0003_auto_20180501_0100'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filetype',
            options={'verbose_name': '文档目录', 'verbose_name_plural': '文档目录'},
        ),
    ]
