# Generated by Django 2.0.4 on 2018-04-30 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0004_auto_20180501_0102'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='categoryPerm',
            field=models.ManyToManyField(to='cmdb.FileType', verbose_name='可查看的目录'),
        ),
    ]
