# Generated by Django 2.0.4 on 2018-04-30 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0005_myuser_categoryperm'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filetype',
            options={'verbose_name': '目录管理', 'verbose_name_plural': '目录管理'},
        ),
        migrations.AlterModelOptions(
            name='myuser',
            options={'verbose_name': '用户管理', 'verbose_name_plural': '用户管理'},
        ),
    ]
