# Generated by Django 2.0.4 on 2018-04-30 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0006_auto_20180501_0142'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fileinfo',
            options={'permissions': (('read_fileinfo', '可读权限'),), 'verbose_name': '文档资源', 'verbose_name_plural': '文档资源'},
        ),
    ]
