# Generated by Django 2.0.4 on 2018-04-30 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0007_auto_20180501_0148'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fileinfo',
            options={'verbose_name': '文档资源', 'verbose_name_plural': '文档资源'},
        ),
    ]
