# Generated by Django 2.0.4 on 2018-04-30 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0008_auto_20180501_0227'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fileinfo',
            options={'permissions': (('read_fileinfo', '可读权限'),), 'verbose_name': '文档资源', 'verbose_name_plural': '文档资源'},
        ),
    ]
