# Generated by Django 2.0.4 on 2018-05-01 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0011_auto_20180501_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileinfo',
            name='categoryStr',
            field=models.CharField(default='test', editable=False, max_length=128),
        ),
        migrations.AlterField(
            model_name='fileinfo',
            name='fileOsPath',
            field=models.CharField(default='test', editable=False, max_length=128),
        ),
        migrations.AlterField(
            model_name='fileinfo',
            name='swfOsPath',
            field=models.CharField(default='test', editable=False, max_length=128),
        ),
        migrations.AlterField(
            model_name='fileinfo',
            name='swfPath',
            field=models.CharField(default='test', editable=False, max_length=128),
        ),
    ]
